eval_binary="build/tasks/setcover/setcover"
eval_output_dir="results/evaluation"
eval_score_direction="minimize"

eval_instances=(
  "data/sc_157_0"
  "data/sc_330_0"
  "data/sc_1000_11"
  "data/sc_5000_1"
  "data/sc_10000_5"
  "data/sc_10000_2"
)

eval_three_thresholds=(130000 29 240 70 120 280)
eval_five_thresholds=(94402 24 147 31 64 167)
