eval_binary="build/tasks/tsp/tsp"
eval_output_dir="results/evaluation"
eval_score_direction="minimize"

eval_instances=(
  "data/tsp_51_1"
  "data/tsp_100_3"
  "data/tsp_200_2"
  "data/tsp_574_1"
  "data/tsp_1889_1"
  "data/tsp_33810_1"
)

eval_three_thresholds=(482 23433 35985 40000 378069 78478868)
eval_five_thresholds=(430 20800 30000 37600 323000 67700000)
